# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

ZSH_THEME=""

# Plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

# Options
ENABLE_CORRECTION="true"

source $ZSH/oh-my-zsh.sh

# User configuration
export PATH="$HOME/.local/bin:$PATH"

# oh-my-posh prompt
eval "$(oh-my-posh init zsh --config ~/.config/ohmyposh/server.toml)"
